
name: 'My Custom Action'
description: 'A simple custom GitHub Action'
author: 'Your Name'
inputs:
  my_input:
    description: 'A sample input'
    required: true
    default: 'default_value'
outputs:
  my_output:
    description: 'The output of the action'
runs:
  using: 'node12'
  main: 'dist/main.js'

