name: "My Node.js GitHub Action"
description: "A simple GitHub Action using Node.js, Docker, and @actions/core"
author: "Your Name"

inputs:
  message:
    description: "Message to print"
    required: true
    default: "Hello, GitHub Actions!"

runs:
  using: "docker"
  image: "Dockerfile"
