name: Test Custom Action

on:
  push:
    branches:
      - main

jobs:
  custom-action-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my custom action
        uses: joechiu/my-custom-action@v1.0.6
        with:
					message: "Hello from my Node.js Action!"

