name: Test Custom Node.js Action

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom Node.js action
        uses: ./ # Points to the local custom action
        with:
          message: "Hello from my Node.js Action!"

# on:
#   push:
#     branches:
#       - main
# 
# jobs:
#   test-action:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
# 
#       - name: Run custom Node.js action
#         uses: ./ # Points to the local custom action
#         with:
#           message: "Hello from my Node.js Action!"
# 
# name: Test Custom Action
# 
# on:
#   push:
#     branches:
#       - main
# 
# jobs:
#   custom-action-job:
#     runs-on: ubuntu-latest
# 
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
# 
#       - name: Run my custom action
#         uses: joechiu/my-custom-action@v1.0.6
#         with:
# 					message: "Hello from my Node.js Action!"
# 
# name: Test Custom Node.js Action

